# Version of Docker compose file 
# version: '3.8' 

services:
  mysqldb:
    image: mysql:latest
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports: 
      - 3306:3306
    volumes: 
      - vol-dev-mysql-db:/var/lib/mysql
volumes:
  vol-dev-mysql-db: